class RouteNames {
  RouteNames._();

  static const String welcome = 'welcome';
  static const String login = 'login';
  static const String register = 'register';
  static const String forgotPassword = 'forgot_password';
  static const String passwordResetSent = 'password_reset_sent';
  static const String setNewPassword = 'set_new_password';
  static const String passwordUpdated = 'password_updated';
  static const String verifyEmailSent = 'verify_email_sent';
  static const String emailVerified = 'email_verified';
  static const String authCallback = 'auth_callback';
  static const String magicLink = 'magic_link';
  static const String magicLinkSent = 'magic_link_sent';
  static const String otpRequest = 'otp_request';
  static const String otpVerify = 'otp_verify';
  static const String mfaSetup = 'mfa_setup';
  static const String mfaChallenge = 'mfa_challenge';
  static const String home = 'home';
  static const String admin = 'admin';
  static const String adminFlags = 'admin_flags';
  static const String adminPlans = 'admin_plans';
  static const String adminBranding = 'admin_branding';
  static const String adminCoupons = 'admin_coupons';
  static const String adminTrash = 'admin_trash';
  static const String adminChangelog = 'admin_changelog';
  static const String changelog = 'changelog';
  static const String adminAppBranding = 'admin_app_branding';
  static const String setup = 'setup';
  static const String adminEmailLog = 'admin_email_log';
  static const String adminUsers = 'admin_users';
  static const String adminUserDetail = 'admin_user_detail';
  static const String adminMetrics = 'admin_metrics';
  static const String accountSettings = 'account_settings';
  static const String changePassword = 'change_password';
  static const String changePasswordDone = 'change_password_done';
  static const String changeEmail = 'change_email';
  static const String changeEmailSent = 'change_email_sent';
  static const String emailChanged = 'email_changed';
  static const String deleteAccount = 'delete_account';
  static const String passkeys = 'passkeys';
  static const String sessions = 'sessions';
  static const String files = 'files';
  static const String tokens = 'tokens';
  static const String webhooks = 'webhooks';
  static const String webhookDetail = 'webhook_detail';
  static const String notifications = 'notifications';
  static const String onboarding = 'onboarding';
  static const String auditLog = 'audit_log';
  static const String activity = 'activity';
  static const String team = 'team';
  static const String acceptInvite = 'accept_invite';
  static const String plans = 'plans';
  static const String billingSuccess = 'billing_success';
  static const String billingInfo = 'billing_info';
  static const String embeddedCheckout = 'embedded_checkout';
  static const String invoices = 'invoices';
  static const String terms = 'terms';
  static const String privacy = 'privacy';
  static const String cookies = 'cookies';
  static const String notFound = 'not_found';
}

class RoutePaths {
  RoutePaths._();

  static const String welcome = '/';
  static const String login = '/login';
  static const String register = '/register';
  static const String forgotPassword = '/forgot-password';
  static const String passwordResetSent = '/password-reset-sent';
  static const String setNewPassword = '/set-new-password';
  static const String passwordUpdated = '/password-updated';
  static const String verifyEmailSent = '/verify-email-sent';
  static const String emailVerified = '/email-verified';
  static const String authCallback = '/auth/callback';
  static const String magicLink = '/magic-link';
  static const String magicLinkSent = '/magic-link-sent';
  static const String otpRequest = '/otp';
  // NO usar paths anidados sin GoRoute padre. go_router se confunde si
  // `/otp/verify` es ruta plana mientras existe `/otp` como ruta plana
  // independiente — dispara `assert(uri.path.startsWith(matchedLocation))`.
  static const String otpVerify = '/otp-verify';
  static const String mfaSetup = '/mfa-setup';
  static const String mfaChallenge = '/mfa-challenge';
  static const String home = '/home';
  static const String admin = '/admin';
  static const String adminFlags = '/admin/flags';
  static const String adminPlans = '/admin/plans';
  static const String adminBranding = '/admin/branding';
  static const String adminCoupons = '/admin/coupons';
  static const String adminTrash = '/admin/trash';
  static const String adminChangelog = '/admin/changelog';
  static const String changelog = '/changelog';
  static const String adminAppBranding = '/admin/app-branding';
  static const String setup = '/setup';
  static const String adminEmailLog = '/admin/email-log';
  static const String adminUsers = '/admin/users';
  static const String adminUserDetail = '/admin/users/:id';
  static const String adminMetrics = '/admin/metrics';
  static const String accountSettings = '/account-settings';
  static const String changePassword = '/change-password';
  static const String changePasswordDone = '/change-password-done';
  static const String changeEmail = '/change-email';
  static const String changeEmailSent = '/change-email-sent';
  static const String emailChanged = '/email-changed';
  static const String deleteAccount = '/delete-account';
  static const String passkeys = '/passkeys';
  static const String sessions = '/account-settings/sessions';
  static const String files = '/account-settings/files';
  static const String tokens = '/account-settings/tokens';
  static const String webhooks = '/account-settings/webhooks';
  // Detalle de endpoint; el `:id` lo rellena GoRouter desde
  // `pathParameters: {'id': endpointId}` o `state.pathParameters['id']`.
  static const String webhookDetail = '/account-settings/webhooks/:id';
  static const String notifications = '/notifications';
  static const String onboarding = '/onboarding';
  static const String auditLog = '/audit-log';
  static const String activity = '/activity';
  static const String team = '/team';
  static const String acceptInvite = '/accept-invite';
  static const String plans = '/billing/plans';
  static const String billingSuccess = '/billing/success';
  static const String billingInfo = '/billing/info';
  static const String embeddedCheckout = '/billing/checkout';
  static const String invoices = '/billing/invoices';
  static const String terms = '/terms';
  static const String privacy = '/privacy';
  static const String cookies = '/cookies';
}
